In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt



In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
%cd /content/drive/MyDrive/Colab Notebooks

/content/drive/MyDrive/Colab Notebooks


In [4]:
import pickle

In [5]:
sc = pickle.load(open('svm_sc.sav', 'rb'))

In [6]:
preinput=sc.transform([[3,76.45994832,0,2,0,1,1,0,0,148.1126761,22,0.7,137.528754,4.62724359,10.7,34,12300,4.705597015,0,0,0,1,1,0,0
,1,1]])
preinput

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[-3.00463205e+00, -1.15074630e-02, -6.83842759e-01,
         1.65360436e+00, -1.96101988e+00, -1.12118037e+00,
        -3.70983846e-01, -1.30631566e+01, -2.05626670e+00,
         5.01640246e+01, -2.09252295e+00, -3.46464565e+00,
         1.62759313e+02,  1.11750329e+01,  2.49066053e+01,
         9.02384980e+01,  9.05692619e+04,  1.13515023e+01,
        -1.95866374e+00, -3.42997170e-01, -2.35702260e-01,
         1.35269628e+00,  1.35269628e+00, -2.92770022e-01,
        -1.93649167e+00,  1.91485422e+00,  2.24620893e+00]])

In [9]:
preinput

array([[-3.00463205e+00, -1.15074630e-02, -6.83842759e-01,
         1.65360436e+00, -1.96101988e+00, -1.12118037e+00,
        -3.70983846e-01, -1.30631566e+01, -2.05626670e+00,
         5.01640246e+01, -2.09252295e+00, -3.46464565e+00,
         1.62759313e+02,  1.11750329e+01,  2.49066053e+01,
         9.02384980e+01,  9.05692619e+04,  1.13515023e+01,
        -1.95866374e+00, -3.42997170e-01, -2.35702260e-01,
         1.35269628e+00,  1.35269628e+00, -2.92770022e-01,
        -1.93649167e+00,  1.91485422e+00,  2.24620893e+00]])

In [15]:
loaded_model = pickle.load(open('svm_Grid.sav', 'rb'))

In [16]:
result = loaded_model.predict(preinput)

In [18]:
result

array([ True])